// Staleness Detector state: the concept check-list, on the same writable /state
// volume as Ask history (see history/store.ts) — /data is read-only, and this is
// exactly the kind of small, single-file, single-user state that volume exists
// for. Concepts live in one file so "review" is just editing a status field in
// place; there's no separate proposed/active split to keep in sync.
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join, resolve, sep } from "node:path";
import { getStateDir } from "../history/store";
import type { ConceptList, RunStatus, StalenessReport } from "./types";

const CONCEPTS_DIR = "staleness";
const CONCEPTS_FILE = "concepts.json";
const REPORTS_DIR = "reports";
const RUN_STATUS_FILE = "run-status.json";

// runId is generated by the loop itself (toRunId() below), never from outside
// input — but a filename derived from a timestamp still gets the same
// containment guard as everything else here, for defense in depth.
const RUN_ID_PATTERN = /^[0-9TZ-]+$/;

/** Turn a Date into a filesystem-safe report id (colons/dots stripped). */
export function toRunId(at: Date): string {
  return at.toISOString().replace(/[:.]/g, "-");
}

// Guard the fixed relative path against the (env-provided) state dir, mirroring
// historyPath() — the path is constant so this always passes, but it validates
// before any filesystem access.
function conceptsPath(): string {
  const base = resolve(getStateDir());
  const target = resolve(base, CONCEPTS_DIR, CONCEPTS_FILE);
  if (target !== join(base, CONCEPTS_DIR, CONCEPTS_FILE) || !target.startsWith(base + sep)) {
    throw new Error("unsafe concepts path");
  }
  return target;
}

const EMPTY_LIST: ConceptList = { generatedAt: "", concepts: [] };

/** The concept check-list, or an empty list if bootstrap hasn't run yet. */
export async function readConceptList(): Promise<ConceptList> {
  try {
    const text = await readFile(conceptsPath(), "utf8");
    const parsed = JSON.parse(text) as ConceptList;
    if (!Array.isArray(parsed.concepts)) return EMPTY_LIST;
    return parsed;
  } catch {
    return EMPTY_LIST; // no file yet, or unreadable
  }
}

export async function writeConceptList(list: ConceptList): Promise<void> {
  const base = resolve(getStateDir());
  await mkdir(join(base, CONCEPTS_DIR), { recursive: true });
  await writeFile(conceptsPath(), JSON.stringify(list, null, 2) + "\n", "utf8");
}

function reportPath(runId: string): string {
  if (!RUN_ID_PATTERN.test(runId)) throw new Error(`unsafe runId: ${runId}`);
  const base = resolve(getStateDir());
  const target = resolve(base, CONCEPTS_DIR, REPORTS_DIR, `${runId}.json`);
  if (!target.startsWith(base + sep)) throw new Error("unsafe report path");
  return target;
}

export async function writeReport(report: StalenessReport): Promise<void> {
  const base = resolve(getStateDir());
  await mkdir(join(base, CONCEPTS_DIR, REPORTS_DIR), { recursive: true });
  await writeFile(reportPath(report.runId), JSON.stringify(report, null, 2) + "\n", "utf8");
}

export async function readReport(runId: string): Promise<StalenessReport | null> {
  try {
    return JSON.parse(await readFile(reportPath(runId), "utf8")) as StalenessReport;
  } catch {
    return null;
  }
}

/** Every stored runId, most recent first (runIds are ISO timestamps, so this is
 *  also chronological order). */
export async function listReportIds(): Promise<string[]> {
  try {
    const base = resolve(getStateDir());
    const files = await readdir(join(base, CONCEPTS_DIR, REPORTS_DIR));
    return files
      .filter((f) => f.endsWith(".json"))
      .map((f) => f.slice(0, -".json".length))
      .sort()
      .reverse();
  } catch {
    return [];
  }
}

function runStatusPath(): string {
  const base = resolve(getStateDir());
  const target = resolve(base, CONCEPTS_DIR, RUN_STATUS_FILE);
  if (target !== join(base, CONCEPTS_DIR, RUN_STATUS_FILE) || !target.startsWith(base + sep)) {
    throw new Error("unsafe run-status path");
  }
  return target;
}

const EMPTY_RUN_STATUS: RunStatus = {
  lastRunStartedAt: null,
  lastRunCompletedAt: null,
  lastRunStatus: null,
  lastRunFlaggedCount: 0,
  nextScheduledRun: null,
};

export async function readRunStatus(): Promise<RunStatus> {
  try {
    return JSON.parse(await readFile(runStatusPath(), "utf8")) as RunStatus;
  } catch {
    return EMPTY_RUN_STATUS;
  }
}

export async function writeRunStatus(status: RunStatus): Promise<void> {
  const base = resolve(getStateDir());
  await mkdir(join(base, CONCEPTS_DIR), { recursive: true });
  await writeFile(runStatusPath(), JSON.stringify(status, null, 2) + "\n", "utf8");
}
