// Reads and validates the auth-related environment variables. All four are
// generated by `npm run provision:auth` and supplied to the container via its
// env file — see .env.example. Kept in one place so a missing/short value fails
// loudly at first use rather than silently degrading security.

/** The single user's credentials (everything except the cookie secret). */
export interface AuthCredentials {
  username: string;
  passwordHash: string; // argon2id PHC string
  totpSecret: string; // base32
}

/** Credentials used to verify a login attempt. */
export function getAuthConfig(): AuthCredentials {
  return {
    username: requireEnv("AUTH_USERNAME"),
    passwordHash: requireEnv("AUTH_PASSWORD_HASH"),
    totpSecret: requireEnv("TOTP_SECRET"),
  };
}

/** Secret that seals the iron-session cookie. iron-session requires >= 32 chars. */
export function getSessionSecret(): string {
  const secret = requireEnv("SESSION_SECRET");
  if (secret.length < 32) {
    throw new Error("SESSION_SECRET must be at least 32 characters (iron-session requirement)");
  }
  return secret;
}

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required env var ${name} — run 'npm run provision:auth' to generate credentials`);
  }
  return value;
}
